---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an EC2 instance and runs a Python script on it'
Parameters:
  UserDataFile:
    Type: String
    Description: User data script contents

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # ImageId: 'ami-0a261c0e5f51090b1' # amazon linux
      ImageId: 'ami-0039da1f3917fa8e3' # ubuntu 22.04
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData: !Ref UserDataFile
      IamInstanceProfile: !Ref DemoInstanceProfile

  DemoInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: demo-ec2-instance-profile
      Path: /
      Roles:
       - !Ref DemoEc2InstanceRole

  DemoEc2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: demo-ec2-instance-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: Everithing
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"



#      IamInstanceProfile: !Ref MyRole
#
#  MyRole:
#    Type: "AWS::IAM::Role"
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: "Allow"
#            Principal:
#              Service: "ec2.amazonaws.com"
#            Action: "sts:AssumeRole"
#      Path: "/"
#      ManagedPolicyArns:
#        - "arn:aws:iam::aws:policy/AdministratorAccess"


Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - PublicIp
