# org: aljeshishe3
# app: ec2scheduler


service: ec2scheduler
provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  timeout: 30
  ecr:
    images:
      appimage:
         path: ./ec2scheduler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - '*'
      Resource: "*"
package:
  include:
    - ec2scheduler/**
functions:
    handler:
      image: appimage
#      events:
#      - schedule: rate(10 minutes)
      environment:
        TASK: docker run python:3.11 bash -c "git clone https://github.com/aljeshishe/ec2scheduler && cd ec2scheduler && make task"
