# org: aljeshishe3
# app: ec2scheduler


service: ec2scheduler
provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  ecr:
    images:
      appimage:
        path: ./
  iamRoleStatements:
    - Effect: Allow
      Action:
        - '*'
      Resource: "*"

functions:
    handler:
      image: appimage
#        handler: handler.handler
#        events:
#        - schedule: rate(5 minutes)
